#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.                                                         
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/dilanrinconhbtn permanent;/" /etc/nginx/sites-available\
/default
sudo service nginx start
